<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="cdpr" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="cable_mass" value="0.001" /> <!-- arbitrary value for mass -->
  <xacro:property name="cable_radius" value="0.001" /> 
  <xacro:property name="frame_color" value="orange" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="frame_lower" value="1.0 1.0 0" />
  <xacro:property name="frame_radius" value="0.02" />
  <xacro:property name="frame_lenght" value="2" />
  <xacro:property name="frame_type" value="box" />

  <xacro:property name="cable_color" value="blue" />
  <xacro:property name="cable_lenght" value="3.4641016151377544" />
  <xacro:property name="cable_radius" value="0.005" />

  <xacro:property name="platform_size" value="0.3" />
  <xacro:property name="platform_color" value="red" />
  <xacro:property name="platform_pos_x" value="0.3" />
  <xacro:property name="platform_pos_y" value="0.3" />
  <xacro:property name="platform_pos_z" value="0.5" />
  <xacro:property name="platform_pos_rpy" value="0" />
  <xacro:property name="platform_mass" value="5" />
  <xacro:property name="platform_iaa" value="0.33" /> <!-- ixx iyy izz-->
  <xacro:property name="platform_iab" value="0" /> 

  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" />


  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find cdpr)/urdf/rrbot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find cdpr)/urdf/materials.xacro" />
  <xacro:include filename="$(find cdpr)/sdf/cube1.xacro" />


  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="frame"/>
  </joint>

  <!-- Base Link -->
  <link name="frame_1">
    <collision>
      <origin xyz="${-frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${-frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="${-frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link>

  <joint name="joint1" type="fixed">
    <parent link="frame_1"/>
    <child link="frame_2"/>
    <origin xyz="${-frame_lenght/2} ${-frame_lenght/2} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>


  <link name="frame_2">
    <collision>
      <origin xyz="0 ${frame_lenght/2} 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 ${frame_lenght/2} 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="0 ${frame_lenght/2} 0" rpy="${PI/2} 0 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link>

  <joint name="joint2" type="fixed">
    <parent link="frame_2"/>
    <child link="frame_3"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint>

  <link name="frame_3">
    <collision>
      <origin xyz="0 ${-frame_lenght/2} 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 ${-frame_lenght/2} 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="0 ${-frame_lenght/2} 0" rpy="0 ${PI/2} 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link>

  <link name="frame_4">
    <collision>
      <origin xyz="${-frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${-frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="${-frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link>

  <link name="frame_5">
    <collision>
      <origin xyz="${frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="${frame_lenght/2} ${frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link> 

  <link name="frame_6">
    <collision>
      <origin xyz="${frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="${frame_lenght/2} ${-frame_lenght/2} ${frame_lenght/2}" rpy="0 0 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link> 

  <link name="frame_7">
    <collision>
      <origin xyz="0 ${frame_lenght/2} 0" rpy="0 ${-PI/2} 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 ${frame_lenght/2} 0" rpy="0 ${-PI/2} 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="0 ${frame_lenght/2} ${frame_lenght/2}" rpy="0 ${-PI/2} 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link> 

  <link name="frame_8">
    <collision>
      <origin xyz="${frame_lenght/2} 0 0" rpy="0 ${-PI/2} 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${frame_lenght/2} 0 0" rpy="${-PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="${frame_lenght/2} 0 0" rpy="0 ${-PI/2} 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link> 

  <link name="frame_9">
    <collision>
      <origin xyz="${frame_lenght/2} 0 ${frame_lenght}" rpy="0 ${-PI/2} 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${frame_lenght/2} 0 ${frame_lenght}" rpy="${-PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="${frame_lenght/2} 0 ${frame_lenght}" rpy="0 ${-PI/2} 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link> 

  <link name="frame_10">
    <collision>
      <origin xyz="0 ${frame_lenght/2} ${frame_lenght}" rpy="0 ${-PI/2} 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 ${frame_lenght/2} ${frame_lenght}" rpy="0 ${-PI/2} 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="0 ${frame_lenght/2} ${frame_lenght}" rpy="0 ${-PI/2} 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link> 


  <link name="frame_11">
    <collision>
      <origin xyz="${-frame_lenght/2} 0 ${frame_lenght}" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${-frame_lenght/2} 0 ${frame_lenght}" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="${-frame_lenght/2} 0 ${frame_lenght}" rpy="${PI/2} 0 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link>

  <link name="frame_12">
    <collision>
      <origin xyz="0 ${-frame_lenght/2} ${frame_lenght}" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 ${-frame_lenght/2} ${frame_lenght}" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="${frame_radius}" length="${frame_lenght}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>
    <inertial>
      <origin xyz="0 ${-frame_lenght/2} ${frame_lenght}" rpy="0 ${PI/2} 0"/>
      <mass value="10000"/>
      <inertia
	  ixx="10000" ixy="0.0" ixz="0.0"
	  iyy="10000" iyz="0.0"
	  izz="$10000"/>
    </inertial>
  </link>


  <link name="platform">
    <collision>
      <origin xyz="${platform_pos_x} ${platform_pos_y} ${platform_pos_z}" 
      rpy="${platform_pos_rpy} ${platform_pos_rpy} ${platform_pos_rpy}"/>
      <geometry>
        <box size="${platform_size} ${platform_size} ${platform_size}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${platform_pos_x} ${platform_pos_y} ${platform_pos_z}" 
      rpy="${platform_pos_rpy} ${platform_pos_rpy} ${platform_pos_rpy}"/>
      <geometry>
        <box size="${platform_size} ${platform_size} ${platform_size}"/>
      </geometry>
      <material name="${platform_color}"/>
    </visual>
    <inertial>
      <origin xyz="${platform_pos_x} ${platform_pos_y} ${platform_pos_z}" 
      rpy="${platform_pos_rpy} ${platform_pos_rpy} ${platform_pos_rpy}"/>
      <mass value="${platform_mass}"/>
      <inertia
	  ixx="${platform_iaa}" ixy="${platform_iab}" ixz="${platform_iab}"
	  iyy="${platform_iaa}" iyz="${platform_iab}"
	  izz="${platform_iaa}"/>
    </inertial>
  </link>

 <xacro:macro name="default_cable" 
  params="numero xyz_x xyz_y xyz_z rpy_x rpy_y rpy_z">
  <link name="cable${numero}">
    <collision>
      <origin xyz="${xyz_x} ${xyz_y} ${xyz_z}" 
              rpy="${rpy_x} ${rpy_y} ${rpy_z}"/>
      <geometry>
        <cylinder radius="${cable_radius}" length="${cable_lenght}"/>
      </geometry>
    </collision>
    <visual>
      <!--
      <origin xyz="${xyz_x} ${xyz_y} ${xyz_z}" 
              rpy="${rpy_x} ${rpy_y} ${rpy_z}"/> -->
    <origin name="cable0"/>
      <geometry>
        <cylinder radius="${cable_radius}" length="${cable_lenght}"/>
      </geometry>
      <material name="${cable_color}"/>
    </visual>
    <inertial>
      <origin xyz="${xyz_x} ${xyz_y} ${xyz_z}" 
              rpy="${rpy_x} ${rpy_y} ${rpy_z}"/>
      <mass value="${cable_mass}"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
        iyy="0.001" iyz="0.0"
        izz="0.001"/>
    </inertial>
  </link>
</xacro:macro>

<xacro:default_cable numero="0" xyz_x="-0.792380" xyz_y="-0.792380" xyz_z="1.756272"
rpy_x="-2.436024" rpy_y="0.575296" rpy_z="-1.353793" />
<xacro:default_cable numero="1" xyz_x="-0.922769" xyz_y="0.963064 " xyz_z="1.909338"
rpy_x="2.754717" rpy_y="0.667932" rpy_z="2.113659" />


  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="${frame_color}"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${height3 - axel_offset/2}" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="hokuyo_link"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://rrbot_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${camera_link} 0 ${height3 - axel_offset*2}" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <joint name="camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
  </joint>

  <link name="camera_link_optical">
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
