cdpr:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: cable0
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: cable2
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: cable2
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: cable3
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: cable4
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: cable5
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: cable6
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: cable7
    pid: { p: 100.0, i: 0.01, d: 10.0 }
